# GitHub Actions workflow to publish the Blockcoins package to PyPI
# Triggered when a new release is published
# More info: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish Blockcoins to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build distributions
        run: python -m build

      - name: Upload built distributions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blockcoins-dist
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/blockcoins/

    steps:
      - name: Download built distributions
        uses: actions/download-artifact@v4
        with:
          name: blockcoins-dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
